/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sotrc.client.gui;

import java.awt.Color;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

import sotrc.client.*;

/**
 *
 * @author spencer
 */
public class ChatWindow extends javax.swing.JFrame {
    ClientManager manager;
    public String chatterUsername;
    private UUID chatID;
    private FingerprintState state;
    private boolean active;
    /**
     * Creates new form ChatWindow
     */
    public ChatWindow(UUID uuid, ClientManager man, String username) {
        manager = man;
        chatterUsername = username;
        chatID = uuid;
        state = FingerprintState.NEITHER;
        active = true;
        initComponents();
        setupComponents();
    }
    
    public ChatWindow(UUID uuid, ClientManager man, String username, FingerprintState state) {
        manager = man;
        chatterUsername = username;
        chatID = uuid;
        this.state = state;
        initComponents();
        setupComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewMessagesScroll = new javax.swing.JScrollPane();
        txtChatArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTypeChat = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        reportUserButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtChatArea.setBackground(new java.awt.Color(248, 248, 248));
        txtChatArea.setColumns(20);
        txtChatArea.setLineWrap(true);
        txtChatArea.setRows(5);
        txtChatArea.setDisabledTextColor(new java.awt.Color(13, 1, 1));
        txtChatArea.setFocusable(false);
        viewMessagesScroll.setViewportView(txtChatArea);

        txtTypeChat.setColumns(20);
        txtTypeChat.setLineWrap(true);
        txtTypeChat.setRows(5);
        jScrollPane2.setViewportView(txtTypeChat);

        sendButton.setBackground(new java.awt.Color(250, 238, 238));
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        reportUserButton.setForeground(new java.awt.Color(9, 15, 243));
        reportUserButton.setText("Report User");
        reportUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportUserButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportUserButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportUserButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewMessagesScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reportUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewMessagesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(reportUserButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = txtTypeChat.getText();
        if(message.isEmpty()){
            System.out.println("Cannot sent blank message");
            return;
        } else {
            if(manager.sendMessage(chatID, message)) {
                String postChat = manager.getCurrentUsername() + ": \n" + message + "\n";
                txtChatArea.append(postChat);
                
                txtTypeChat.setText("");
            } else { // Chat failed
                System.out.println("Chat failed to send...");
            }
            
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void reportUserButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportUserButtonMouseEntered
        reportUserButton.setForeground(Color.RED);
    }//GEN-LAST:event_reportUserButtonMouseEntered

    private void reportUserButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportUserButtonMouseExited
        reportUserButton.setForeground(Color.BLUE);
    }//GEN-LAST:event_reportUserButtonMouseExited

    private void reportUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportUserButtonMouseClicked
        System.out.println("Report Clicked");
        int selectedOption = JOptionPane.showConfirmDialog(null,
                                            "Are you sure you want to report this user?",
                                            "Report user?",
                                            JOptionPane.YES_NO_OPTION);
        if (selectedOption != JOptionPane.YES_OPTION) return;
        if (!manager.reportUser(chatterUsername)) {
            JOptionPane.showMessageDialog(this, "Could not report user. Maybe the chat has become inactive.", "SOTRC", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("User Reported");
    }//GEN-LAST:event_reportUserButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(active)
            this.setVisible(false);
        else
            this.dispose();
    }//GEN-LAST:event_formWindowClosing

    public void incomingMessage(String username, String message) {
        String postChat = username + ":\n" + message + "\n";
        txtChatArea.append(postChat);
    }

    public void statusMessage(String message) {
        txtChatArea.append(message);
    }
    
    public UUID getUUID() {
        return chatID;
    }
    
    /*
    public boolean isVerified() {
        return verified;
    }
    */
    
    /**
     * side effect: inauthentic resets background of contentpane.
     */
    public void setState(FingerprintState state) {
        this.state = state;
        setPaneBackground();
    }
    
    public void disableActions() {
        txtTypeChat.setEnabled(false);
        reportUserButton.setEnabled(false);
        sendButton.setEnabled(false);
        active = false;
    }
    
    private void setPaneBackground() {
        this.getContentPane().setBackground(
              state == FingerprintState.AUTHENTIC ? SotrcActionsGUI.VERIFIED_COLOR
            : state == FingerprintState.INAUTHENTIC ? SotrcActionsGUI.INAUTHENTIC_COLOR
            : Color.LIGHT_GRAY
            );
    }

    private void setupComponents() {
        txtChatArea.setEditable(false);
        DefaultCaret caret = (DefaultCaret) txtChatArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        setPaneBackground();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow(null, null, "TESTING").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel reportUserButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea txtChatArea;
    private javax.swing.JTextArea txtTypeChat;
    private javax.swing.JScrollPane viewMessagesScroll;
    // End of variables declaration//GEN-END:variables
}
