/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sotrc.client.gui;

import common.network.SslDefaults;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sotrc.client.ClientManager;

/**
 *
 * @author spencer
 */
public class SotrcClientGUI extends javax.swing.JFrame {
	private ClientManager manager;
	/**
	 * Creates new form SotrcClientGUI
	 */
	public SotrcClientGUI(String host, String portStr) {
		int port = SslDefaults.DEFAULT_SOTRC_PORT;
		try {
			port = Integer.parseInt(portStr);
		} catch (NumberFormatException e) {
			System.out.println("Using port " + SslDefaults.DEFAULT_SOTRC_PORT + ".");
			port = SslDefaults.DEFAULT_SOTRC_PORT;
		}

		manager = new ClientManager(host, port);
		initComponents();
		checkOnlineStatus();
	}
	public SotrcClientGUI(String host) {
		this(host, Integer.toString(SslDefaults.DEFAULT_SOTRC_PORT));
	}
	public SotrcClientGUI() {
		this(SslDefaults.DEFAULT_HOST, Integer.toString(SslDefaults.DEFAULT_SOTRC_PORT));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		createAccountButton = new javax.swing.JButton();
		loginButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
		jLabel1.setText("SOTRC");

		jLabel2.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
		jLabel2.setText("adjective |  \\ˌe-sə-ˈter-ik\\");

			jLabel3.setText("intended for or likely to be understood by only a small ");

			jLabel4.setText("number of people with a specialized knowledge or interest.");

			createAccountButton.setText("Create Account");
			createAccountButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					createAccountButtonActionPerformed(evt);
				}
			});

			loginButton.setText("Login");
			loginButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					loginButtonActionPerformed(evt);
				}
			});

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
							.addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel1)
							.addComponent(jLabel2)
							.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel4)))
					.addContainerGap(21, Short.MAX_VALUE))
			);
			layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel1)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jLabel2)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jLabel3)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jLabel4)
					.addGap(28, 28, 28)
					.addComponent(createAccountButton)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(loginButton)
					.addContainerGap(32, Short.MAX_VALUE))
			);

			pack();
		}// </editor-fold>//GEN-END:initComponents

	private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
		AccountCreateGUI frame = new AccountCreateGUI(manager,this);
		frame.setTitle("SOTRC");
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}//GEN-LAST:event_createAccountButtonActionPerformed

	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		LoginGUI frame = new LoginGUI(manager, this);
		frame.setTitle("SOTRC");
		frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
		this.setVisible(false);
	}//GEN-LAST:event_loginButtonActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		manager.shutdown();
		this.dispose();
	}//GEN-LAST:event_formWindowClosing

	
	public void checkOnlineStatus() {
		if(!manager.isConnectedToServer()) {
			createAccountButton.setEnabled(false);
			loginButton.setEnabled(false);
			JOptionPane.showMessageDialog(this, "Cannot connect to server. Please try again later.", "SOTRC", JOptionPane.ERROR_MESSAGE);
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args[]) {
		if (!checkArgs(args))
				System.exit(0);
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SotrcClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SotrcClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SotrcClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SotrcClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				SotrcClientGUI gui = new SotrcClientGUI(args[0],
									(args.length == 1 ? Integer.toString(SslDefaults.DEFAULT_SOTRC_PORT): args[1]));
				gui.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
				gui.setVisible(true);
			}
		});
	}
	
	private static boolean checkArgs(final String[] args) {
			if (args.length == 0) {
					System.out.println(" Usage: java sotrc.client.gui.SotrcClientGUI <host> [<port>]");
					return false;
			}

			return true;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton createAccountButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JButton loginButton;
	// End of variables declaration//GEN-END:variables
}
