/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sand.client.gui;

import java.util.Arrays;

import javax.swing.JOptionPane;
import common.*;
import sand.client.*;

/**
 *
 * @author spencer
 */
public class EditUserInfoGUI extends javax.swing.JFrame {
    SandClientManager manager;
    /**
     * Creates new form EditUserInfoGUI
     */
    public EditUserInfoGUI(SandClientManager man) {
        manager = man;
        initComponents();
        authenticationBox.setSelected(manager.needsTwoFactorAuthentication());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        editUsernamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtoldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        editUsernameButton = new javax.swing.JButton();
        UpdatePasswordPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pswdConfirm = new javax.swing.JPasswordField();
        pswdNew = new javax.swing.JPasswordField();
        pswdOld = new javax.swing.JPasswordField();
        updatePasswordButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        authenticationBox = new javax.swing.JCheckBox();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editUsernamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Username"));

        jLabel1.setText("Old Username");

        jLabel2.setText("New Username");

        editUsernameButton.setText("Submit");
        editUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsernameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editUsernamePanelLayout = new javax.swing.GroupLayout(editUsernamePanel);
        editUsernamePanel.setLayout(editUsernamePanelLayout);
        editUsernamePanelLayout.setHorizontalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editUsernamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtoldUsername))
                    .addGroup(editUsernamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewUsername))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUsernamePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editUsernameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        editUsernamePanelLayout.setVerticalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtoldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editUsernameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UpdatePasswordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Password"));

        jLabel3.setText("Old Password");

        jLabel4.setText("New Password");

        jLabel5.setText("Confirm Pasword");

        updatePasswordButton.setText("Submit");
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePasswordPanelLayout = new javax.swing.GroupLayout(UpdatePasswordPanel);
        UpdatePasswordPanel.setLayout(UpdatePasswordPanelLayout);
        UpdatePasswordPanelLayout.setHorizontalGroup(
            UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UpdatePasswordPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updatePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdatePasswordPanelLayout.createSequentialGroup()
                        .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswdConfirm)
                            .addComponent(pswdNew)
                            .addComponent(pswdOld))))
                .addContainerGap())
        );
        UpdatePasswordPanelLayout.setVerticalGroup(
            UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pswdOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pswdNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(UpdatePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pswdConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatePasswordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("2 Factor Authentication"));

        authenticationBox.setText("Enable 2-factor Authentication");
        authenticationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticationBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authenticationBox)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(authenticationBox)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editUsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdatePasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editUsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdatePasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsernameButtonActionPerformed
        String oldUsername = txtoldUsername.getText();
        String newUsername = txtNewUsername.getText();
        if(oldUsername.equals("") || newUsername.equals("")) {
            // These are required
            JOptionPane.showMessageDialog(this, "Both Old Username and New Username are required", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
            return;
	    } else if(!manager.getCurrentUsername().equals(oldUsername)) {
	    	JOptionPane.showMessageDialog(this, "Old Username doesn't match your current username", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
            return;
	    } else {
	    	int selectedOption = JOptionPane.showConfirmDialog(null,
                    "Are you sure you want to make this change?\n"
                    + "Old Username: "+oldUsername+"\n"
                    + "New Username: "+newUsername,
                    "Change Username?",
                    JOptionPane.YES_NO_OPTION);
	    	if (selectedOption == JOptionPane.YES_OPTION) {
	    		if(manager.changeUsername(newUsername)) {
		    		txtoldUsername.setText("");
		    		txtNewUsername.setText("");
		    		JOptionPane.showMessageDialog(this, "Username changed", SandClientGUI.popUpTitle, JOptionPane.INFORMATION_MESSAGE);
	    		} else {
	    			JOptionPane.showMessageDialog(this, "Update username failed.", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
	    		}
	    	} // else do nothing
	    }
    }//GEN-LAST:event_editUsernameButtonActionPerformed

    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        char[] oldPass = pswdOld.getPassword();
    	char[] newPass = pswdNew.getPassword();
        char[] confirmPass = pswdConfirm.getPassword();

        if(!Arrays.equals(newPass, confirmPass)) {
                System.out.println("Passwords do not match!");
                JOptionPane.showMessageDialog(this, "Passwords do not match!", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
        } else if(!LoginUtilities.guidelineChecker(String.valueOf(newPass))) {
                System.out.println("Password does not meet requirements");
                JOptionPane.showMessageDialog(this, "Password does not meet requirements", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
        } else {
        	int selectedOption = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to change your password?\n",
                    "Change Password?",
                    JOptionPane.YES_NO_OPTION);
	    	if (selectedOption == JOptionPane.YES_OPTION) {
	    		if(manager.changePassword(oldPass, newPass)){
	    			pswdOld.setText("");
		    		pswdNew.setText("");
		    		pswdConfirm.setText("");
                    JOptionPane.showMessageDialog(this, "Password changed", SandClientGUI.popUpTitle, JOptionPane.INFORMATION_MESSAGE);
                } else {
                    System.out.println("Password not changed");
                    JOptionPane.showMessageDialog(this, "Password not changedr", SandClientGUI.popUpTitle, JOptionPane.ERROR_MESSAGE);
                }
	    	}
        }
    }//GEN-LAST:event_updatePasswordButtonActionPerformed

    private void authenticationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticationBoxActionPerformed
        boolean isOn = authenticationBox.isSelected();
        if(isOn) {
                int selectedOption = JOptionPane.showConfirmDialog(this,
                        "Have you set up 2-Factor Authentication before?",
                        "2-Factor Authentication",
                        JOptionPane.YES_NO_OPTION);
                if(selectedOption == JOptionPane.NO_OPTION) {
                    //Show the QRCode GUI
                    String qrLocation = manager.getTwoFactorQRCode();
                    System.out.println(qrLocation);
                    QRCodeGUI dialog = new QRCodeGUI(new javax.swing.JFrame(), true, qrLocation);
                    dialog.setVisible(true);
                } // else just enable it

                JOptionPane.showMessageDialog(this, "Two factor is now enabled", SandClientGUI.popUpTitle, JOptionPane.INFORMATION_MESSAGE);
                manager.toggleTwoFactor(isOn);

        } else {
                JOptionPane.showMessageDialog(this, "Two factor is now disabled", SandClientGUI.popUpTitle, JOptionPane.INFORMATION_MESSAGE);
                manager.toggleTwoFactor(isOn);
        }
    }//GEN-LAST:event_authenticationBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserInfoGUI(new SandClientManager()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdatePasswordPanel;
    private javax.swing.JCheckBox authenticationBox;
    private javax.swing.JButton editUsernameButton;
    private javax.swing.JPanel editUsernamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField pswdConfirm;
    private javax.swing.JPasswordField pswdNew;
    private javax.swing.JPasswordField pswdOld;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtoldUsername;
    private javax.swing.JButton updatePasswordButton;
    // End of variables declaration//GEN-END:variables
}
