package common;

import java.io.*;
import java.util.*;

public class DefaultProperties {
	public static final String SAND_LOOKUP_DIR = "../data/sand-data/lookups/"; // CredentialLookup by host
	public static final String SAND_DATA_DIR = "../data/sand-data/data/"; // CredentialTuple
	public static final String SAND_ACCOUNTS_DIR = "../data/sand-data/accounts/"; // UserAccount
	public static final String SAND_SALTS_DIR = "../data/sand-data/salts/"; // account salts
	public static final String SOTRC_LOOKUP_DIR = "../data/sotrc-data/lookups/";
	public static final String SOTRC_DATA_DIR = "../data/sotrc-data/data/";
	public static final String SOTRC_ACCOUNTS_DIR = "../data/sotrc-data/accounts/";
	public static final String SOTRC_SALTS_DIR = "../data/sotrc-data/salts/";

	/**
	 * Constructs the default.properties file.
	 */
	public static void main(String[] args) throws Exception {
		FileOutputStream fos = new FileOutputStream("../default.properties");
		Properties defaultProperties = new Properties();
		defaultProperties.setProperty("sand.lookupDir", SAND_LOOKUP_DIR);
		defaultProperties.setProperty("sand.dataDir", SAND_DATA_DIR);
		defaultProperties.setProperty("sand.accountsDir", SAND_ACCOUNTS_DIR);
		defaultProperties.setProperty("sand.saltsDir", SAND_SALTS_DIR);

		defaultProperties.setProperty("sotrc.lookupDir", SOTRC_LOOKUP_DIR);
		defaultProperties.setProperty("sotrc.dataDir", SOTRC_DATA_DIR);
		defaultProperties.setProperty("sotrc.accountsDir", SOTRC_ACCOUNTS_DIR);
		defaultProperties.setProperty("sotrc.saltsDir", SOTRC_SALTS_DIR);

		defaultProperties.store(fos,
			"SAND/SOTRC properties. Generated by main of common.DefaultProperties");
	}
}
